### ISSUE TITLE
Doesn't ignore respelling guides

### ISSUE THREAD

**Issue by oxguy3** [seangransee/WikiLoopr#3]
There are a few articles that have respelling pronunciation guides in the introduction sentence, which should be ignored as italics, but instead, WikiLoopr follows them to the page "Help:Pronunciation respelling key". An example of an article like this is [Massachusetts](https://en.wikipedia.org/wiki/Massachusetts).

**Comment by seangransee** [comment]
Thanks for the bug report! The issue has been fixed, and the page for [Massachusetts](www.wikiloopr.com/Massachusetts) should work now.
